# ファイルを読み取り専用のボリュームとして追加して、コンテナからそれを読み取ることでConfigMapを使用する例
apiVersion: v1
kind: ConfigMap
metadata: 
  name: test-file
data: # ボリュームの中にConfigMapをファイル形式で作成、以下のようなキーにファイルの名前、値にそのファイルの中身を書く。複数行に渡る場合は「|」を付ける。
  data.csv: |
    name,age,email,password
    naka,1,naka@example.com,j4gn43g4gr
    tanaka,2,tanaka@example.com,8j437fkw3v

--- 
apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
spec: 
  restartPolicy: Never
  containers: 
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "sleep", "3600" ]
      volumeMounts: 
        - name: config # 下のボリュームの名前に対応させることでConfigMapをマウントができる
          mountPath: "/datadir" # この配下にdata.csvをマウントする
          readOnly: true
  volumes: # ボリュームはコンテナの外に書いてあげる、インデントの位置に気を付ける
    - name: config
      configMap: 
        name: test-file # ConfigMapの名前は上で作成したConfigMapの名前と一致させること




